### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Fortist** [aksource/MultiToolHolders#1]
すみません。
Im not good at Japanese, so I wont bother. Anyway, I got a crash when I tried out this with Metallurgy's pickaxe.

http://pastebin.com/W0717VKD

Thank you for checking.

**Comment by aksource** [comment]
Thank you for informing bug.
I apologize to you for delay commenting.
Your error is fixed at AdvancedTools 2.1g.
I tested MultiToolHolder1.3d and AdvancedTools 2.1k and confirmed it work fine.
Enjoy Playing!!
